### ISSUE TITLE
Generación de contexto de base de datos

### ISSUE THREAD

**Issue by Aval0G** [SSC-UdeC/Gimnasio#4]
:sparkles: [Generacion de contexto de Base de datos]

:mag: Descripción

Se generará él .cs del BDContext de la base de datos

:bulb: Propuesta

*Generacion de archivo .cs con el DBContext

un ejemplo seria:
![image](https://github.com/user-attachments/assets/41d0f105-38d6-46b5-9342-7e0936b13cac)

:memo: Notas adicionales

Referencia de la base de datos:
https://lucid.app/lucidchart/c05afc6f-2a23-470c-9158-323a88fec75a/edit?viewport_loc=-216%2C-470%2C2392%2C1200%2C0_0&invitationId=inv_e91e07ec-a7d6-46ea-b41c-ae1cf8dbcf9b
https://render2web.com/blazor/creacion-de-una-aplicacion-crud-en-blazor-server/

**Comment by Lpineda0** [comment]
Se realizo el contexto de la base de datos, pendiente de otras partes para probar su funcionalidad.

![DBC](https://github.com/user-attachments/assets/18def140-49be-4da1-a3a3-3a12f8d6adb6)

**Comment by Aval0G** [comment]
![image](https://github.com/user-attachments/assets/9adc0a38-94f8-41b8-8c74-1e29c3a329b0)
Correcion echa
