### ISSUE TITLE
Creación de las Interfaces para la bd

### ISSUE THREAD

**Issue by Aval0G** [SSC-UdeC/Gimnasio#6]
:sparkles: [Nombre de la feature]

:mag: Descripción

Se crearan las interfaces para las tablas de la BD con los metodos basicos de CRUD

:bulb: Propuesta

Se creara un archivo para cada interfaz donde vendran los metodos que tiene cada repositorio estos estaran en una carpeta llamada repositorio
![image](https://github.com/user-attachments/assets/d7199ce3-2de8-4f00-8d77-6a24e53cfa84)
y cada archivo con sus respectivos metodos que tendra por ejemplo:
![image](https://github.com/user-attachments/assets/e08b2343-0a4b-46b6-adcc-54ba0178075f)

:memo: Notas adicionales

https://render2web.com/blazor/creacion-de-una-aplicacion-crud-en-blazor-server/

**Comment by Troll4478** [comment]
Se añadió el repositorio de las interfaces de cada tabla de la base de datos. Ahora cada tabla cuenta con su respectiva interfaz para realizar operaciones CRUD (Create, Read, Update, Delete).

Con las tablas afectadas: `Clientes`, `Visitas`

![Repositorio](https://github.com/user-attachments/assets/794077f8-8932-454a-b668-a0fa25b2e4be)

**Interfaz de Clientes:**
![3fffbeb2-e26e-498b-8bf4-b0b9f6d72f16](https://github.com/user-attachments/assets/38271a51-19ec-4f5e-8a3b-a3d99ae581e7)

**Métodos implementados (`Clientes`):**
![73daeb48-6cba-47ac-9515-464eeba910de](https://github.com/user-attachments/assets/c578aa8d-0a3d-4536-ab47-fec0a34de6af)

**Interfaz de Visitas:**
![9ea89b45-de1e-4f0c-b96b-8274f14f48fd](https://github.com/user-attachments/assets/896c7771-bacf-4ca5-8c48-7467f3cd4d7d)

**Métodos implementados (`Visitas`):**
![809324f4-fed2-4d2e-a031-cf65831eee4a](https://github.com/user-attachments/assets/7610afa7-1622-45d3-af4d-a6819bfbd6c3)

**Comment by Aval0G** [comment]
Revisado
